Recommender frontend
LDomadia/c-546-group-19-project pull request #45
Opened 2022-05-01 13:10 UTC by AlephEleven

added outfits/generate route:

allows you to choose clothes preferences (defined in data/gen_clothes.js), then saves & displays generated outfit, as a list of clothing cards.

2022-05-01 15:49 UTC, LDomadia requested changes
Which inputs are supposed to be required? Is it just the name or are all inputs required?
<img width="1386" alt="Screen Shot 2022-05-01 at 11 48 22 AM" src="https://user-images.githubusercontent.com/62802533/166153713-eb87a084-2376-4233-bd1a-eb6333f89809.png">

also need to add a link from the My Outfits page to the Generate Outfit form page

2022-05-01 16:50 UTC, AlephEleven commented
> Which inputs are supposed to be required? Is it just the name or are all inputs required? <img alt="Screen Shot 2022-05-01 at 11 48 22 AM" width="1386" src="https://user-images.githubusercontent.com/62802533/166153713-eb87a084-2376-4233-bd1a-eb6333f89809.png">
> 
> also need to add a link from the My Outfits page to the Generate Outfit form page

got it, all parts are required, but there isnt a my outfits page yet so that can be done by whoevers making it

2022-05-01 16:58 UTC, AlephEleven commented
updated

2022-05-01 22:19 UTC, AlephEleven commented
fixed merge conflict

2022-05-01 22:36 UTC, uityh requested changes, later dismissed

2022-05-01 22:36 UTC, uityh commented on routes/index.js
> +const outfitsRoutes = require("./outfits");
there are two of these which cause an error

2022-05-02 01:43 UTC, LDomadia approved these changes

2022-05-02 01:44 UTC, merged